FROM skilldlabs/php:56
MAINTAINER Andy Postnikov <andypost@ya.ru>

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
  php5-xdebug

# Settings for xdebug added in parent image
