FROM skilldlabs/php:7
MAINTAINER Andy Postnikov <andypost@ya.ru>

RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  php7-xdebug

# Settings for xdebug added in parent image
